jobs:
  - name: ms-eureka-manifest-job
    type: manifest
    steps:
      - IN: cntr-eureka
      - IN: docker-options-eureka     
  
  - name: ms-eureka-deploy-job
    type: deploy
    steps:
      - IN: ms-eureka-manifest-job
      - IN: gcr-cluster