jobs:
# Configuration for catalog service
  - name: ms-catalog-manifest-job
    type: manifest
    steps:
      - IN: cntr-catalog
      - IN: docker-options-catalog

  - name: ms-catalog-deploy-job
    type: deploy
    steps:
      - IN: ms-catalog-manifest-job
      - IN: aws-cluster

